version: "3.8"

services:
  fuschia:
    build:
      context: .
      args:
        MIX_ENV: test
      cache_from:
        - ghcr.io/cciuenf/fuschia_ci:latest
    image: ghcr.io/cciuenf/fuschia_ci:latest
    container_name: pescarte_fuschia_ci
    depends_on:
      - db
    volumes:
      - /fuschia/deps
      - /fuschia/_build
    env_file:
      - .env-sample
    environment:
      - MIX_ENV=test

  db:
    image: ghcr.io/cciuenf/pescarte_db:latest
    container_name: pescarte_fuschia_db
    environment:
      - POSTGRES_USER=pescarte
      - POSTGRES_PASSWORD=pescarte
      - POSTGRES_DB=pescarte
